import { RuleTester } from "oxlint/plugins-dev";

import { noMockingRule } from "./no-mocking.ts";

const tester = new RuleTester({ languageOptions: { parserOptions: { lang: "ts" } } });
const mocking = { messageId: "mocking" };
const mockAssertion = { messageId: "mockAssertion" };
const mockImport = { messageId: "mockImport" };

tester.run("anti-slop/no-mocking", noMockingRule, {
  valid: [
    ...[
      ["vitest", "vi"], ["vite-plus/test", "vi"], ["@vitest/spy", "vi"], ["@jest/globals", "jest"],
    ].map(([module, api]) => ({
      code: `import { ${api} } from '${module}'; ${api}.useFakeTimers(); const clock = ${api}; clock.useFakeTimers(); const start = ${api}.useFakeTimers; start(); const { useFakeTimers: renamed, useRealTimers: reset = fallback } = ${api}; renamed(); reset(); const bound = ${api}.useFakeTimers.bind(${api}); bound();`, options: [{ modules: [] }],
    })),
    "const vi = { useFakeTimers() {} }; const jest = { useFakeTimers() {} }; vi.useFakeTimers(); jest.useFakeTimers();",
    ...["vi", "jest"].map((api) => `${api}.useFakeTimers(); const clock = ${api}; clock.useFakeTimers(); const start = ${api}.useFakeTimers; start(); const { useFakeTimers: renamed, useRealTimers: reset = fallback } = ${api}; renamed(); reset(); const bound = ${api}.useFakeTimers.bind(${api}); bound();`),
    "const { fn: make = fallback } = service; make();",
    "const service = { fn() {} }; const make = (service.fn.bind as typeof service.fn.bind)(service); make();",
    { code: "import { nonMocking } from '@vitest/spy'; nonMocking();", options: [{ modules: [] }] },
    ...["service.fn as typeof service.fn", "service.fn satisfies typeof service.fn", "service.fn!", "<typeof service.fn>service.fn", "(service.fn)"].flatMap((expression) => [
      `(${expression})();`,
      `const make = ${expression}; make();`,
      `const make = (${expression}).bind(service); make();`,
    ]),
    ...["service as typeof service", "service satisfies typeof service", "service!", "<typeof service>service", "(service)"].map((expression) => `(${expression}).fn();`),
    "const service = { mock: { other: 1 } }; const value = (service.mock as typeof service.mock).other;",
    "const store = new InMemoryUserStore();",
    "expect(x).toBe(1);",
    "const vi = { mock() {}, fn() {}, spyOn() {} }; vi.mock(); vi.fn(); vi.spyOn();",
    "function test(jest: { mock(): void }) { jest.mock(); }",
    "import { vi as localVi } from './helpers'; localVi.mock('./module');",
    "import { vi } from './helpers'; vi.fn();",
    "import { jest } from './helpers'; jest.spyOn(store, 'save');",
    "function makeStub() {} makeStub(); function stubFn() {} stubFn(); function spyOn() {} spyOn();",
    "const vi = { fn() {}, spyOn() {} }; const makeStub = vi.fn; makeStub(); const { fn: stubFn, spyOn } = vi; stubFn(); spyOn(); const spy = vi.spyOn.bind(vi); spy(); const m = vi; m.fn();",
    "import { vi } from './helpers'; const makeStub = vi.fn; makeStub(); const { fn: stubFn } = vi; stubFn(); const m = vi; m.fn();",
    "import { fn, spyOn } from './helpers'; fn(); spyOn();",
    "import { vi } from 'vitest'; function test(vi: { fn(): void }) { const makeStub = vi.fn; makeStub(); const m = vi; m.fn(); }",
    "import { jest } from '@jest/globals'; function test(jest: { spyOn(): void }) { const spy = jest.spyOn.bind(jest); spy(); }",
    "import { vi } from 'vitest'; const { useFakeTimers: clock } = vi; clock();",
    "import { vi } from 'vite-plus/test'; vi.useFakeTimers();",
    "import { vi } from 'vitest'; const makeStub = service.fn; makeStub();",
    "import { vi } from 'vitest'; const { [method]: stubFn } = vi; stubFn();",
    "import { vi } from 'vitest'; const { fn: stubFn = fallback } = service; stubFn();",
    "import { vi } from 'vitest'; let makeStub = vi.fn; makeStub = realFunction; makeStub();",
    "import { vi } from 'vitest'; let m = vi; m = service; m.fn();",
    "const makeStub = stubFn; const stubFn = makeStub; makeStub();",
    "const vi = service; const jest = service; const m = vi; m.fn(); const j = jest; j.spyOn();",
    "const store = { save() {} }; const alias = store; alias.save();",
    "import { vi } from 'vitest'; const makeStub = vi.fn; function test(makeStub: () => void) { makeStub(); }",
    "import { vi } from 'vitest-extra'; const makeStub = vi.fn; makeStub();",
    "import { vi } from 'vite-plus/test-extra'; const m = vi; m.fn();",
    "const service = { mock() {} }; service.mock();",
    "vi.useFakeTimers(); jest.setSystemTime(0);",
    "vi[method]();",
    "service.mock; service.calls; service.mock.other; service[method]();",
    "import { Mock } from './types';",
    "import { expect, test, type ExpectStatic } from 'vitest';",
    "import 'fake-indexeddb'; import { MemoryStorage } from './memory-storage';",
    "import FakeTimers from '@sinonjs/fake-timers';",
    "import client from 'msw-extra'; import helper from 'sinon-helper';",
    "import helper from '@example/helper'; import('./helper'); require('./helper');",
    "import(moduleName); require(moduleName); require();",
    { code: "import 'sinon'; import('msw/node'); require('nock');", options: [{ modules: [] }] },
    { code: "import 'msw';", options: [{ modules: ["custom-mocks"] }] },
    { code: "import 'custom-mocks-extra';", options: [{ modules: ["custom-mocks"] }] },
    { code: "import 'custom-mocks';", options: [{}] },
  ],
  invalid: [
    { code: "import { vi } from '@vitest/spy'; const { fn: make = fallback } = vi; make();", errors: [mockImport, mocking] },
    ...["vi.fn as typeof vi.fn", "vi.fn satisfies typeof vi.fn", "vi.fn!", "<typeof vi.fn>vi.fn", "(vi.fn)"].flatMap((expression) => [
      { code: `import { vi } from 'vitest'; (${expression})();`, errors: [mocking] },
      { code: `import { vi } from 'vitest'; const make = ${expression}; make();`, errors: [mocking] },
      { code: `import { vi } from 'vitest'; const make = (${expression}).bind(vi); make();`, errors: [mocking] },
    ]),
    ...["vi as typeof vi", "vi satisfies typeof vi", "vi!", "<typeof vi>vi", "(vi)"].flatMap((expression) => [
      { code: `import { vi } from 'vitest'; (${expression}).fn();`, errors: [mocking] },
      { code: `import { vi } from 'vitest'; const api = ${expression}; api.fn();`, errors: [mocking] },
      { code: `import { vi } from 'vitest'; const { fn: make } = ${expression}; make();`, errors: [mocking] },
    ]),
    { code: "import { vi } from 'vitest'; const make = (vi.fn.bind as typeof vi.fn.bind)(vi); make();", errors: [mocking] },
    { code: "(handler.mockReturnValue as typeof handler.mockReturnValue)(1);", errors: [mocking] },
    { code: "(expect(handler).toHaveBeenCalled satisfies Function)();", errors: [mockAssertion] },
    { code: "const value = (handler.mock as typeof handler.mock).calls;", errors: [mockAssertion] },
    ...[
      "fn", "spyOn", "mock", "doMock", "unmock", "doUnmock", "unstable_mockModule",
      "importMock", "importActual", "mocked", "hoisted", "stubGlobal", "stubEnv",
      "unstubAllGlobals", "unstubAllEnvs", "restoreAllMocks", "resetAllMocks", "clearAllMocks",
      "isMockFunction",
    ].flatMap((method) => [
      { code: `vi.${method}();`, errors: [mocking] },
      { code: `jest.${method}();`, errors: [mocking] },
    ]),
    { code: "vi['fn']();", errors: [mocking] },
    { code: "jest['spyOn'](store, 'save');", errors: [mocking] },
    { code: "import { vi } from 'vitest'; vi.mock('./user-store');", errors: [mocking] },
    { code: "import { vi as testApi } from 'vitest'; testApi.fn();", errors: [mocking] },
    { code: "import { jest } from '@jest/globals'; jest.spyOn(store, 'save');", errors: [mocking] },
    { code: "import { jest as testApi } from '@jest/globals'; testApi['doMock']('./store');", errors: [mocking] },
    ...[
      ["vitest", "vi"],
      ["vite-plus/test", "vi"],
      ["@jest/globals", "jest"],
    ].flatMap(([module, api]) => [
      { code: `import { ${api} } from '${module}'; ${api}.fn();`, errors: [mocking] },
      { code: `import { ${api} } from '${module}'; const makeStub = ${api}.fn; makeStub();`, errors: [mocking] },
      { code: `import { ${api} } from '${module}'; const { fn: stubFn, spyOn } = ${api}; stubFn(); spyOn();`, errors: [mocking, mocking] },
      { code: `import { ${api} } from '${module}'; const spy = ${api}.spyOn.bind(${api}); spy(store, 'save');`, errors: [mocking] },
      { code: `import { ${api} } from '${module}'; const m = ${api}; m.fn();`, errors: [mocking] },
      { code: `import { ${api} as testApi } from '${module}'; const makeStub = testApi['fn']; const another = makeStub; another();`, errors: [mocking] },
      { code: `import { ${api} } from '${module}'; const m = ${api}; const { spyOn: spy } = m; spy(store, 'save');`, errors: [mocking] },
      { code: `import { ${api} } from '${module}'; const m = ${api}; const another = m; another['spyOn'](store, 'save');`, errors: [mocking] },
      { code: `import { ${api} } from '${module}'; const { ['fn']: stubFn } = ${api}; stubFn();`, errors: [mocking] },
      { code: `import { ${api} } from '${module}'; const { fn: stubFn = fallback } = ${api}; stubFn();`, errors: [mocking] },
      { code: `import { ${api} } from '${module}'; const makeStub = ${api}.fn; function test() { makeStub(); }`, errors: [mocking] },
      { code: `import { ${api} } from '${module}'; const makeStub = ${api}.fn; const spy = makeStub.bind(${api}); spy();`, errors: [mocking] },
    ]),
    { code: "const makeStub = vi.fn; makeStub();", errors: [mocking] },
    { code: "const { fn: stubFn, spyOn } = vi; stubFn(); spyOn();", errors: [mocking, mocking] },
    { code: "const spy = vi.spyOn.bind(vi); spy();", errors: [mocking] },
    { code: "const m = vi; m.fn();", errors: [mocking] },
    { code: "const makeStub = jest.fn; makeStub();", errors: [mocking] },
    { code: "const { fn: stubFn, spyOn } = jest; stubFn(); spyOn();", errors: [mocking, mocking] },
    { code: "const spy = jest.spyOn.bind(jest); spy();", errors: [mocking] },
    { code: "const m = jest; m.fn();", errors: [mocking] },
    { code: "import { vi } from '@vitest/spy'; vi.fn();", errors: [mockImport, mocking] },
    { code: "import { fn, spyOn } from '@vitest/spy'; fn(); spyOn(store, 'save');", errors: [mockImport, mocking, mocking] },
    { code: "import { fn as makeStub } from '@vitest/spy'; const stubFn = makeStub; stubFn();", errors: [mockImport, mocking] },
    { code: "import { vi } from '@vitest/spy'; const makeStub = vi.fn; makeStub();", errors: [mockImport, mocking] },
    { code: "import { vi } from '@vitest/spy'; const { fn: stubFn, spyOn } = vi; stubFn(); spyOn();", errors: [mockImport, mocking, mocking] },
    { code: "import { vi } from '@vitest/spy'; const spy = vi.spyOn.bind(vi); spy();", errors: [mockImport, mocking] },
    { code: "import { vi } from '@vitest/spy'; const m = vi; m.fn();", errors: [mockImport, mocking] },
    { code: "import * as spies from '@vitest/spy'; spies.fn();", errors: [mockImport, mocking] },
    { code: "import * as spies from '@vitest/spy'; const { fn: stubFn } = spies; stubFn();", errors: [mockImport, mocking] },
    { code: "import { fn } from '@vitest/spy'; fn();", options: [{ modules: [] }], errors: [mocking] },
    { code: "import('@vitest/spy');", errors: [mockImport] },
    { code: "require('@vitest/spy');", errors: [mockImport] },
    ...[
      "mockImplementation", "mockImplementationOnce", "mockReturnValue", "mockReturnValueOnce",
      "mockResolvedValue", "mockResolvedValueOnce", "mockRejectedValue", "mockRejectedValueOnce",
      "mockReturnThis", "mockClear", "mockReset", "mockRestore", "mockName",
    ].map((method) => ({ code: `handler.${method}();`, errors: [mocking] })),
    { code: "handler['mockReturnValue'](1);", errors: [mocking] },
    { code: "handler.mockName('save').mockReturnThis();", errors: [mocking, mocking] },
    ...[
      "toHaveBeenCalled", "toHaveBeenCalledTimes", "toHaveBeenCalledWith", "toHaveBeenLastCalledWith",
      "toHaveBeenNthCalledWith", "toHaveBeenCalledOnce", "toHaveReturned", "toHaveReturnedTimes",
      "toHaveReturnedWith", "toHaveLastReturnedWith", "toHaveNthReturnedWith", "toBeCalled",
      "toBeCalledTimes", "toBeCalledWith", "lastCalledWith", "nthCalledWith", "toReturn",
      "toReturnTimes", "toReturnWith", "lastReturnedWith", "nthReturnedWith",
    ].map((method) => ({ code: `expect(handler).${method}();`, errors: [mockAssertion] })),
    { code: "expect(handler).not.toHaveBeenCalled();", errors: [mockAssertion] },
    { code: "expect(p).resolves.toHaveReturnedWith(1);", errors: [mockAssertion] },
    { code: "expect(p).rejects.toHaveBeenCalledWith('error');", errors: [mockAssertion] },
    { code: "expect(handler)['toBeCalled']();", errors: [mockAssertion] },
    { code: "assertions.toHaveBeenCalled();", errors: [mockAssertion] },
    ...["calls", "results", "lastCall", "instances", "invocationCallOrder"].map((property) => ({
      code: `const value = handler.mock.${property};`, errors: [mockAssertion],
    })),
    { code: "expect(handler.mock.calls).toHaveLength(1);", errors: [mockAssertion] },
    { code: "const value = handler['mock']['calls'];", errors: [mockAssertion] },
    ...["vitest", "@jest/globals", "jest-mock"].flatMap((module) =>
      ["Mock", "MockInstance", "Mocked", "MockedFunction", "MockedObject", "MockedClass"].flatMap((name) => [
        { code: `import { ${name} } from '${module}';`, errors: [mockImport] },
        { code: `import type { ${name} as LocalType } from '${module}';`, errors: [mockImport] },
      ]),
    ),
    { code: "import { type Mock, type Mocked } from 'vitest';", errors: [mockImport, mockImport] },
    ...[
      "sinon", "msw", "nock", "fetch-mock", "vitest-mock-extended", "jest-mock-extended",
      "ts-mockito", "testdouble", "aws-sdk-client-mock",
    ].flatMap((module) => [
      { code: `import library from '${module}';`, errors: [mockImport] },
      { code: `import('${module}');`, errors: [mockImport] },
      { code: `require('${module}');`, errors: [mockImport] },
    ]),
    { code: "import { setupServer } from 'msw/node';", errors: [mockImport] },
    { code: "import('msw/node');", errors: [mockImport] },
    { code: "require('msw/node');", errors: [mockImport] },
    { code: "import type { Options } from 'sinon';", errors: [mockImport] },
    { code: "import 'msw';", options: [{}], errors: [mockImport] },
    { code: "import 'custom-mocks';", options: [{ modules: ["custom-mocks"] }], errors: [mockImport] },
    { code: "import('custom-mocks/node');", options: [{ modules: ["custom-mocks"] }], errors: [mockImport] },
    { code: "require('@example/mocks/server');", options: [{ modules: ["@example/mocks"] }], errors: [mockImport] },
    { code: "vi.fn();", options: [{ modules: [] }], errors: [mocking] },
  ],
});
