import { RuleTester } from "oxlint/plugins-dev";

import { noUnsafeMapTypeRule } from "./no-unsafe-map-type.ts";

const tester = new RuleTester({ languageOptions: { parserOptions: { lang: "ts" } } });
const error = { messageId: "unsafeMap" };
const untyped = { messageId: "untypedMap" };

tester.run("anti-slop/no-unsafe-map-type", noUnsafeMapTypeRule, {
	valid: [
		"type Identity<Value> = Value; function read<Value>(): Identity<Value & { id: string }> { return source; }",
		"type Index<Value> = Map<string, Value>; function read<Value>(): Index<Value & { id: string }> { return source; }",
		"type Value = unknown; function make<Value>() { return new Map<string, Value>(); } const values = make<Row>();",
		"function make<Value>() { return <Value extends Row>() => new Map<string, Value>(); } const values = make<unknown>();",
		"function make() { type Value = Row; const values = new Map<string, Value>(); } type Value = unknown;",
		"function make() { type Map<Key, Value> = { key: Key; value: Value }; const values: Map<string, unknown> = input; }",
		"function make(value: unknown) { if (typeof value !== 'string') return; return new Map<string, typeof value>(); }",
		"function make(value: unknown) { if (typeof value === 'string') { return new Map<string, typeof value>(); } }",
		"let value: unknown = input; value = 'text'; type Values = Map<string, typeof value>;",
		"const constructors = [Map, OwnerMap]; constructors[0] = OwnerMap; const Dict = constructors[0]; const values = new Dict<string, unknown>();",
		"const constructors = { Map }; mutate(constructors); const Dict = constructors.Map; const values = new Dict<string, unknown>();",
		"const constructors = { Map }; const alias = constructors; mutate(alias); const Dict = constructors.Map; const values = new Dict<string, unknown>();",
		"const tuple: [string, Row] = [key, row]; type Values = Map<(typeof tuple)[0], (typeof tuple)[1]>;",
		"function make(input: { key: string; value: Row }) { const { key, value } = input; return new Map<typeof key, typeof value>(); }",
		"function make(input: [string, Row]) { const [key, ...rest] = input; const [value] = rest; return new Map<typeof key, typeof value>(); }",
		"function make<Value>() { return new Map<string, Value>(); } const values: Map<string, Row> = make();",
		"function make<Value>(value: Value) { return new Map<string, Value>([[key, value]]); } const values = make(row);",
		"function make<Value = Row>() { return new Map<string, Value>(); } const values = make();",
		"function make<Value extends Row>() { return new Map<string, Value>(); } const values = make();",
		"function make<Value>(value: Value = row) { return new Map<string, Value>(); } const values = make();",
		"class Values<Value> extends Map<string, Value> {} const values: Values<Row> = new Values();",
		"class Values<Value = Row> extends Map<string, Value> {} const values = new Values();",
		"class Values<Value extends Row> extends Map<string, Value> {} const values = new Values();",
		"class Values<Value> { constructor(readonly value: Value) {} entries = new Map<string, Value>(); } const values = new Values(row);",
		"class Base<Value> { entries!: Map<string, Value>; } class Values extends Base<Row> {}",
		"class Left<Value> extends Right<Value> {} class Right<Value> extends Left<Value> {} const values = new Left<unknown>();",
		"function build({ Map: Dict }: typeof owner) { return new Dict<string, unknown>(); }",
		"function build(globalThis: typeof owner) { const { Map: Dict } = globalThis; return new Dict<string, unknown>(); }",
		"const { Map: Ignored, ...rest } = globalThis; const Dict = rest.Map; const values = new Dict<string, unknown>();",
		"const original = next; const next = original; type Values = Map<string, typeof original>;",
		"type Self = Self; const value: Self = input; type Values = Map<string, typeof value>;",
		"function make(input: { value: unknown }) { const value: Row = row; return new Map<string, typeof value>(); }",
		"function make(input: { value: unknown }) { const { value, ...rest } = input; return new Map<string, typeof rest.value>(); }",
		"const { Map: Dict } = owner; const values = new Dict<string, unknown>();",
		"function build(Dict: OwnerConstructor) { return new Dict<string, unknown>(); }",
		"function make<Key, Value>(): Map<Key, Value> { return new Map(); } const values = make<string, Row>();",
		"function make<Value>(value: Value) { return value; } const result = make<unknown>(input);",
		"class Owner<Value> { readonly value: Value; } const values = new Owner<unknown>();",
		"class Owner<Value> extends Map<string, Value> {} const values = new Owner<Row>();",
		"class Owner<Value> { readonly value = new Map<string, Value>(); } const values = new Owner<Row>();",
		"type Box<Value> = { payload: Value }; type Values = Box<unknown>;",
		"const construct = { Map: OwnerMap }; const { Map: Dict } = construct; const values = new Dict<string, unknown>();",
		"let Dict = Map; Dict = OwnerMap; const values = new Dict<string, unknown>();",
		"function make<Value>(): Value { return source; } const value = make<unknown>();",
		{ filename: "values.js", code: "const values = new Map();" },
		{ filename: "values.mjs", code: "const values = new Map();" },
		{ filename: "values.cjs", code: "const values = new Map();" },
		{ filename: "values.jsx", code: "const values = new Map();" },
		"interface Index<Value> extends Map<string, Value> {} type Values = Index<Command>;",
		"interface Left extends Right {} interface Right extends Left {} type Values = Left;",
		"type Values = Map<string, Command>;",
		"type Values = ReadonlyMap<number, Command>;",
		"type Values = WeakMap<object, unknown>;",
		"type Values = Map<string, { payload: unknown }>;",
		"type Values = Map<string, Result<Command, unknown>>;",
		"type Index<Value> = Map<string, Value>; type Values = Index<Command>;",
		"type Index<Value = Command> = Map<string, Value>; const values: Index = new Map();",
		"type Index<Value> = Map<string, Value>; const values: Index<Command> = new Map();",
		"interface Owner { id: string } type Values = Map<string, unknown & Owner>;",
		"interface Owner { id: string } interface Child extends Owner {} type Values = Map<string, Child>;",
		"interface Object { id: string } type Values = Map<string, Object>;",
		"type Map<Key, Value> = { key: Key; value: Value }; type Values = Map<string, unknown>;",
		"type ReadonlyMap<Key, Value> = { key: Key; value: Value }; type Values = ReadonlyMap<string, unknown>;",
		"import { Map } from './owner'; type Values = Map<string, unknown>; const values = new Map();",
		"class Map<Key, Value> {} type Values = Map<string, unknown>; const values = new Map();",
		"function create(Map: Constructor) { const values = new Map(); return values; }",
		"const Map = OwnerMap; const values = new Map<string, unknown>();",
		"const globalThis = owner; const values = new globalThis.Map<string, unknown>();",
		"const values = new Map<string, Command>();",
		"const values: Map<string, Command> = new Map();",
		"const values: ReadonlyMap<string, Command> = new Map([]);",
		"const values = new Map([['key', 1]]);",
		"const values = new Map(entries);",
		"const values = supplied ?? new Map();",
		"const values = { items: new Map() } satisfies Owner;",
		"consume(new Map());",
		"useState<Map<string, Command>>(() => new Map());",
		"const create: () => Map<string, Command> = () => new Map();",
		"const create = (): Map<string, Command> => new Map();",
		"function create(): Map<string, Command> { return new Map(); }",
		"const values = new Map() satisfies Map<string, Command>;",
		"class Owner { values: Map<string, Command> = new Map(); }",
		"class Values extends Map<string, Command> {}",
		"class Values<Value> extends Map<string, Value> {}",
		"interface Values extends ReadonlyMap<string, Command> {}",
		"type Tree = Map<string, Tree>;",
		"type Left = Right; type Right = Left; const values: Left = new Map();",
	],
	invalid: [
		{ code: "type Identity<Value> = Value; function read<Value>(): Identity<Value | Map<string, unknown>> { return source; }", errors: [error] },
		{ code: "const tuple: [string, unknown] = [key, input]; type Bad = Map<(typeof tuple)[0], (typeof tuple)[1]>;", errors: [error] },
		{ code: "function make(input: { key: string; value: unknown }) { const { key, value } = input; return new Map<typeof key, typeof value>(); }", errors: [error] },
		{ code: "function make(input: [string, unknown]) { const [key, value] = input; return new Map<typeof key, typeof value>(); }", errors: [error] },
		{ code: "function make(input: { outer: { key: string; value: unknown } }) { const { outer: { key, value } } = input; return new Map<typeof key, typeof value>(); }", errors: [error] },
		{ code: "function make(input: { key: string; value: unknown; extra: number }) { const { extra, ...rest } = input; return new Map<typeof rest.key, typeof rest.value>(); }", errors: [error] },
		{ code: "function make(...args: [string, unknown]) { const [key, ...rest] = args; const [value] = rest; return new Map<typeof key, typeof value>(); }", errors: [error] },
		{ code: "function make<Args extends [string, unknown]>(...args: Args) { const [key, value] = args; return new Map<typeof key, typeof value>(); }", errors: [error] },
		{ code: "function build({ Map: Dict }: typeof globalThis) { return new Dict<string, unknown>(); }", errors: [error] },
		{ code: "class Base<Value> { entries!: Map<string, Value>; } class Bad extends Base<unknown> {}", errors: [error] },
		{ code: "class Base<Value> extends Map<string, Value> {} class Middle<Value> extends Base<Value> {} const bad = new Middle<unknown>();", errors: [error] },
		{ code: "class Values<Value> extends Map<string, Value> {} const bad = new Values();", errors: [error] },
		{ code: "function make<Value>() { return new Map<string, Value>(); } const bad = make();", errors: [error] },
		{ code: "function make<Value>(input: Value = row) { return new Map<string, Value>(); } const bad = make<unknown>();", errors: [error] },
		{ code: "function make(input: unknown) { return new Map<string, typeof input>(); }", errors: [error] },
		{ code: "const input: unknown = source; const alias = input; type Bad = ReadonlyMap<string, typeof alias>;", errors: [error] },
		{ code: "const { Map: Dict } = globalThis\nconst bad = new Dict<string, unknown>()", errors: [error] },
		{ code: "const { nested: { Map: Dict } } = { nested: globalThis }\nconst bad = new Dict<string, unknown>()", errors: [error] },
		{ code: "const [Dict] = [Map]\nconst bad = new Dict<string, unknown>()", errors: [error] },
		{ code: "const { layers: [{ constructors: { Map: Base } }] } = { layers: [{ constructors: globalThis }] }\nconst Mid = Base\nconst Dict = Mid\nconst bad = new Dict<string, unknown>()", errors: [error] },
		{ code: "const { [\"Map\"]: Dict } = globalThis\nconst bad = new Dict<string, unknown>()", errors: [error] },
		{ code: "function make<K, V>() { return new Map<K, V>() }\nconst bad = make<string, unknown>()", errors: [error] },
		{ code: "const make = <K, V>() => new Map<K, V>()\nconst bad = make<string, unknown>()", errors: [error] },
		{ code: "function make<K, V>(): Map<K, V> { return new Map<K, V>() }\nconst bad = make<string, unknown>()", errors: [error] },
		{ code: "class Wrapper<K, V> extends Map<K, V> {}\nconst bad = new Wrapper<string, unknown>()", errors: [error] },
		{ code: "class Wrapper<K, V> { readonly value = new Map<K, V>() }\nconst bad = new Wrapper<string, unknown>()", errors: [error] },
		{ code: "class Wrapper<K, V> { constructor(readonly value: Map<K, V>) {} }\nconst bad = new Wrapper<string, unknown>(new Map())", errors: [error] },
		{ code: "function make<K, V>() { return { value: new Map<K, V>() } }\nconst bad = make<string, unknown>()", errors: [error] },
		{ code: "function make<K, V>() { return () => new Map<K, V>() }\nconst bad = make<string, unknown>()()", errors: [error] },
		{ code: "function make<K, V>() { return new Map<K, V>() }\nconst alias = make\nconst bad = alias<string, unknown>()", errors: [error] },
		{ code: "type Bag<K, V> = Map<K, V>\nfunction make<K, V>(): Bag<K, V> { return new Map<K, V>() }\nconst bad = make<string, unknown>()", errors: [error] },
		{ code: "interface Bag<K, V> extends Map<K, V> {}\nfunction make<K, V>(): Bag<K, V> { return new Map<K, V>() }\nconst bad = make<string, unknown>()", errors: [error] },
		{ code: "class Wrapper<K, V> { declare readonly value: ReadonlyMap<K, V> }\nconst bad = new Wrapper<string, unknown>()", errors: [error] },
		{ code: "const Wrapper = class<K, V> extends Map<K, V> {}\nconst bad = new Wrapper<string, unknown>()", errors: [error] },
		{ code: "class W<V, K> extends Map<K, V> {}\nconst bad = new W<unknown, string>()", errors: [error] },
		{ code: "class Bag<V> extends Map<string, V> {}\nconst bad = new Bag<unknown>()", errors: [error] },
		{ code: "class Triple<X, V, K> extends Map<K, V> {}\nconst bad = new Triple<0, unknown, string>()", errors: [error] },
		{ code: "function make<V, K>() { return new Map<K, V>() }\nconst bad = make<unknown, string>()", errors: [error] },
		{ code: "function make<V>() { return new Map<string, V>() }\nconst bad = make<unknown>()", errors: [error] },
		{ code: "function make<X, V, K>() { return new Map<K, V>() }\nconst bad = make<0, unknown, string>()", errors: [error] },
		{ code: "class W<V, K> extends Map<K, V> {}\ntype Bad = W<unknown, string>", errors: [error] },
		{ code: "class Bag<V> extends Map<string, V> {}\ntype Bad = Bag<unknown>", errors: [error] },
		{ code: "class Triple<X, V, K> extends Map<K, V> {}\ntype Bad = Triple<0, unknown, string>", errors: [error] },
		{ code: "function build(Dict: typeof Map) { return new Dict<string, unknown>() }", errors: [error] },
		{ code: "type MapType = typeof Map\nfunction build(Dict: MapType) { return new Dict<string, unknown>() }", errors: [error] },
		{ code: "type Index<Value = unknown> = Map<string, Value>;", errors: [error] },
		{ code: "interface Index<Value = unknown> extends ReadonlyMap<string, Value> {}", errors: [error] },
		{ code: "type Box<Value> = { value: Map<string, Value>[] }; type Values = Box<unknown>;", errors: [error] },
		{ code: "type Values = Map<string, NoInfer<unknown>>;", errors: [error] },
		{ code: "type Values = Map<string, [unknown][0]>;", errors: [error] },
		{ code: "interface Values extends Readonly<Map<string, unknown>> {}", errors: [error] },
		{ filename: "values.mts", code: "const values = new Map();", errors: [untyped] },
		{ filename: "values.cts", code: "const values = new Map();", errors: [untyped] },
		{ filename: "values.tsx", code: "const values = new Map();", errors: [untyped] },
		{ code: "interface Index<Value> extends Map<string, Value> {} type Values = Index<unknown>;", errors: [error] },
		{ code: "interface Index<Value> extends ReadonlyMap<string, Value> {} interface Values extends Index<unknown> {}", errors: [error] },
		{ code: "type Values = Map<string, unknown>;", errors: [error] },
		{ code: "type Values = ReadonlyMap<string, unknown>;", errors: [error] },
		{ code: "type Values = Map<number, unknown>;", errors: [error] },
		{ code: "type Values = Map<'known', unknown>;", errors: [error] },
		{ code: "type Values = Map<string, any>;", errors: [error] },
		{ code: "type Values = Map<string, object>;", errors: [error] },
		{ code: "type Values = Map<string, Object>;", errors: [error] },
		{ code: "type Values = Map<string, {}>;", errors: [error] },
		{ code: "type Values = Map<string, Command | unknown>;", errors: [error] },
		{ code: "interface Empty {} type Values = Map<string, Empty>;", errors: [error] },
		{ code: "interface Empty { readonly brand?: never } type Values = Map<string, Empty>;", errors: [error] },
		{ code: "type Payload = unknown; type Values = Map<string, Payload>;", errors: [error] },
		{ code: "type Index<Value> = Map<string, Value>; type Values = Index<unknown>;", errors: [error] },
		{ code: "type Index<Value = unknown> = Map<string, Value>; const values: Index = new Map();", errors: [error] },
		{ code: "type Identity<Value> = Value; type Index<Value, Default = Identity<Value>> = Map<string, Default>; type Values = Index<unknown>;", errors: [error] },
		{ code: "type Optional<Value> = Map<string, Value> | null; type Values = Optional<unknown>;", errors: [error] },
		{ code: "type Values = Readonly<Partial<Map<string, unknown>>>;", errors: [error] },
		{ code: "type Values = Map<string, unknown>; const first: Values = new Map(); const second: Values = new Map();", errors: [error] },
		{ code: "type Values = Map<string, unknown>; type Other = Values;", errors: 2 },
		{ code: "const values = new Map<string, unknown>();", errors: [error] },
		{ code: "const values = new Map<string, any>();", errors: [error] },
		{ code: "const values = new Map<string, object>();", errors: [error] },
		{ code: "const values = new Map<string, {}>();", errors: [error] },
		{ code: "type Payload = unknown; const values = new Map<string, Payload>();", errors: [error] },
		{ code: "const Constructor = Map; const Alias = Constructor; const values = new Alias<string, unknown>();", errors: [error] },
		{ code: "const values = new globalThis.Map<string, unknown>();", errors: [error] },
		{ code: "const values = new globalThis['Map']<string, unknown>();", errors: [error] },
		{ code: "const values = Map<string, unknown>();", errors: [error] },
		{ code: "const values = new Map();", errors: [untyped] },
		{ code: "const values = new Map([]);", errors: [untyped] },
		{ code: "const values = new Map(null);", errors: [untyped] },
		{ code: "const Constructor = Map; const values = new Constructor();", errors: [untyped] },
		{ code: "const create = () => new Map();", errors: [untyped] },
		{ code: "function create() { return new Map(); }", errors: [untyped] },
		{ code: "class Owner { values = new Map(); }", errors: [untyped] },
		{ code: "class Values extends Map<string, unknown> {}", errors: [error] },
		{ code: "const Values = class extends Map<string, object> {};", errors: [error] },
		{ code: "interface Values extends Map<string, unknown> {}", errors: [error] },
		{ code: "interface Values extends ReadonlyMap<string, {}> {}", errors: [error] },
	],
});
